server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

management:
  tracing:
    sampling:
      probability: 1.0


spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/airbnb
    username: root
    password: liviu1986
  cloud:
    config:
      discovery:
        service-id:
      enabled: true
    gateway:
      discovery:
        locator:
          enable: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
booking:
  user:
    missing:
      throwError: false
airbnb:
  placeholder: PCH
