server:
  port: 8060



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: getAllProperties
          uri: lb://AirBnbDemo
          predicates:
            - Path=/properties/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/properties/(?<segment>/*), /api/v1/property/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true
  tracing:
    sampling:
      probability: 1.0